# Generated by Django 5.0.7 on 2025-01-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_remove_product_photo_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
