# Generated by Django 5.0.7 on 2025-01-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_remove_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='photo',
        ),
    ]
